"""Build 5%-step mask variants for menu opacity, independent of vertex alpha.
Uses existing extracted artwork. The regular addon build needs no image libraries.
"""
from io import BytesIO
import json
from pathlib import Path
import struct
from PIL import Image
from build import resource_hash

ROOT=Path(__file__).resolve().parents[1];ART=ROOT/'assets/icons'
SIZE=2048;PITCH=96;INSET=4;EDGE=88;COLS=SIZE//PITCH

def exact_alpha_blocks(image,encoded):
    # Preserve mask endpoints. The default compressor can discard thin peak
    # coverage at intermediate opacity, making the slider visibly inaccurate.
    width,height=image.size;raw=image.getchannel('A').tobytes();cache={};block=0
    for y in range(0,height,4):
        for x in range(0,width,4):
            values=bytes(raw[min(y+j,height-1)*width+min(x+i,width-1)] for j in range(4) for i in range(4))
            payload=cache.get(values)
            if payload is None:
                lo,hi=min(values),max(values)
                palette=[hi,lo]+([(hi*(7-k)+lo*k)//7 for k in range(1,7)] if hi>lo else [hi]*4+[0,255])
                indices={v:min(range(8),key=lambda i:abs(palette[i]-v)) for v in set(values)}
                bits=sum(indices[v]<<(i*3) for i,v in enumerate(values))
                payload=bytes([hi,lo])+bits.to_bytes(6,'little');cache[values]=payload
            encoded[block:block+8]=payload;block+=16
    return encoded

def encode(atlas,prefix,texture,material):
    header=bytearray((ART/'icons.texture.main').read_bytes())
    for at,value in [(204,SIZE),(208,SIZE),(212,SIZE*SIZE),(220,12)]:struct.pack_into('<I',header,at,value)
    gpu=bytearray();mip=atlas
    while True:
        buf=BytesIO();mip.save(buf,format='DDS',pixel_format='DXT5')
        gpu+=exact_alpha_blocks(mip,bytearray(buf.getvalue()[128:]))
        if mip.size==(1,1):break
        mask=mip.getchannel('A').resize((max(1,mip.width//2),max(1,mip.height//2)),Image.Resampling.LANCZOS)
        mip=Image.merge('RGBA',(mask,)*4)
    ink=bytearray((ART/'icons.material.main').read_bytes());struct.pack_into('<Q',ink,140,resource_hash(texture))
    for suffix,data in [('texture.main',header),('texture.gpu_resources',gpu),('material.main',ink)]:
        (ART/(prefix+'.'+suffix)).write_bytes(data)

def build():
    card=json.loads((ART/'manifest.json').read_text())
    cards=Image.open(ART/'mask-atlas.png').convert('RGBA')
    complete=Image.open(ART/'atlas.png').convert('RGBA')
    for marker in [False,True]:
        prefix='marker-opacity' if marker else 'card-opacity'
        texture='mods/retrox/sentry_hud/'+('marker_icons_atlas' if marker else 'icons_atlas')
        material='mods/retrox/sentry_hud/'+('marker_icons_material' if marker else 'icons_material')
        masks=[];cells={}
        for typ,c in sorted(card['cells'].items()):
            layers=[{'uv':c['uv'],'color':[255,255,255]}] if marker else c['layers']
            cells[typ]=[]
            for layer in layers:
                mask=(complete if marker else cards).crop(tuple(round(v*512) for v in layer['uv'])).getchannel('A')
                mask=mask.resize((EDGE,EDGE),Image.Resampling.LANCZOS)
                cells[typ].append({'cell':len(masks),'color':layer['color']});masks.append(mask)
        count=len(masks);assert count*20<=COLS*COLS
        atlas=Image.new('RGBA',(SIZE,SIZE))
        for level in range(1,21):
            for index,source in enumerate(masks):
                slot=(level-1)*count+index;x=(slot%COLS)*PITCH+INSET;y=(slot//COLS)*PITCH+INSET
                mask=source.point(lambda a:round(a*level/20))
                atlas.paste(Image.merge('RGBA',(mask,)*4),(x,y))
                if level==20:
                    for layers in cells.values():
                        for layer in layers:
                            if layer['cell']==index:layer['uv']=[x/SIZE,y/SIZE,(x+EDGE)/SIZE,(y+EDGE)/SIZE]
        encode(atlas,prefix,texture,material)
        info=dict(count=count,columns=COLS,pitch=PITCH,inset=INSET,edge=EDGE,size=SIZE,step=5)
        doc=dict(texture=texture,material=material,texture_hash=f'{resource_hash(texture):016x}',material_hash=f'{resource_hash(material):016x}',opacity=info,cells=cells)
        (ART/(prefix+'.json')).write_text(json.dumps(doc,indent=2)+'\n')
        lua='-- Generated by scripts/build_opacity_icons.py; 5%-step coverage in RGB and alpha.\nreturn {\n'
        lua+=f'    material="{doc["material_hash"]}",texture="{doc["texture_hash"]}",\n'
        lua+='    opacity={'+','.join(f'{k}={v}' for k,v in info.items())+'},\n    cells={\n'
        for typ,layers in cells.items():
            lua+='        ["'+typ+'"]={\n'
            for layer in layers:
                lua+='            {cell='+str(layer['cell'])+',uv={'+','.join(str(v) for v in layer['uv'])+'},color={'+','.join(str(v) for v in layer['color'])+'}},\n'
            lua+='        },\n'
        (ROOT/'src'/('marker_icons.lua' if marker else 'icons.lua')).write_text(lua+'    },\n}\n')
    print('Built independent card/marker opacity atlases: 5% to 100% in 5% steps; 0% hides the GUI')
if __name__=='__main__':build()
